---
- name: Copy values file
  template:
      src: values.yaml.j2
      dest: ~/grafana-values.yaml
  when:
      - inventory_hostname == 'master1a'

- name: Purge previous release
  command: helm del --purge grafana-release
  ignore_errors: yes
  when:
      - inventory_hostname == 'master1a'

- name: Create monitoring ns
  command: kubectl create ns monitoring
  ignore_errors: yes
  when:
      - inventory_hostname == 'master1a'

- pause:
      seconds: 10

- name: Download grafana package
  get_url:
    url: https://github.com/lpereir4/mStakx/blob/master/grafana-3.7.0.tgz?raw=true
    dest: /home/admin/grafana-3.7.0.tgz
  when:
    - inventory_hostname == 'master1a'

- name: Execute helm install
  command: tar zxvf /home/admin/grafana-3.7.0.tgz -C /home/admin/
  when:
    - inventory_hostname == 'master1a'

- name: Execute helm install
  command: helm install --namespace=monitoring --name grafana-release /root/grafana -f /root/grafana-values.yaml
  when:
      - inventory_hostname == 'master1a'
