apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 32727
      protocol: TCP
    - name: https
      port: 443
      nodePort: 32728
      protocol: TCP
  selector:
    app: ingress-nginx
