apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gluster-vol-default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://{{ inventory['gfs_node1'][0].ip }}:8080"
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true