---
- name: "Load lvm kernel modules"
  become: true
  with_items:
      - "dm_snapshot"
      - "dm_mirror"
      - "dm_thin_pool"
  modprobe:
      name: "{{ item }}"
      state: "present"

- name: Remove any existing topology
  file:
    path: /etc/kubernetes/topology.json
    state: absent
  become: yes

- name: "Install glusterfs mount utils (RedHat)"
  become: true
  yum:
      name: "glusterfs-fuse"
      state: "present"
  when: "ansible_os_family == 'RedHat'"
