---

- name: create a instance group
  gcp_compute_instance_group:
    name: test2
    named_ports:
    - name: http
      port: 32727
    network: "{{ network }}"
    zone: us-central1-a
    project: test_project
    auth_kind: serviceaccount
    service_account_file: "/tmp/auth.pem"
    state: present