---
- register: "label_present"
  command: "kubectl --kubeconfig=/home/admin/.kube/config get node --selector=storagenode=glusterfs,kubernetes.io/hostname={{ node }} --ignore-not-found=true"
  changed_when: false

- name: "Assign storage label"
  when: "label_present.stdout_lines|length == 0"
  command: "kubectl --kubeconfig=/home/admin/.kube/config label node {{ node }} storagenode=glusterfs"

- register: "label_present"
  command: "kubectl --kubeconfig=/home/admin/.kube/config get node --selector=storagenode=glusterfs,kubernetes.io/hostname={{ node }} --ignore-not-found=true"
  changed_when: false
- assert: { that: "label_present|length > 0", success_msg: "Node {{ node }} has not been assigned with label storagenode=glusterfs." }
