apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.app.namespace }}
  labels:
    app: guestbook
    tier: frontend
    job: guestbook
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: prom
    port: 9117
    targetPort: 9117
    protocol: TCP
  selector:
    app: guestbook
    tier: frontend
