apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^(/guestbook)$ $1/ permanent;
spec:
  rules:
  - http:
      paths:
        - path: /guestbook/?(.*)
          backend:
            serviceName: frontend
            servicePort: 80
