---
- name: Generate a token
  command: kubeadm token generate
  register: token_command

- set_fact:
    token: "{{ token_command.stdout }}"

- name: Generate kubeadm configuration file
  template:
    src: config.yaml.j2
    dest: /home/admin/config.yaml
    owner: admin
    mode: '0666'
  vars:
    masters:
      - master1a
  become: yes

- name: Launch Kubernetes
  command: kubeadm init --config /home/admin/config.yaml --ignore-preflight-errors=NumCPU
  become: yes

- name: Retrieve join command
  command: kubeadm token create --print-join-command
  register: join_command
  become: yes

- name: "Add K8S Token and Hash to dummy host"
  add_host:
    name:   "JCOM"
    jcom:  "{{ join_command.stdout }}"

- name: Create Kubernetes cluster certificates archive
  archive:
    path: "{{ certificates_dir }}"
    dest: /tmp/pki.tgz
  become: yes

- name: Retrieve Kubernetes cluster certificates archive
  fetch:
    src: "{{ certificates_archive_dir }}"
    dest: "{{ certificates_archive_dir }}"
    flat: yes

- name: Configure kubectl 1/2
  file:
    path: /home/admin/.kube
    state: directory
    mode: '0755'
    owner: "admin" 
    group: "admin"
  become: yes

- name: Configure kubectl 2/2
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/admin/.kube/config
    remote_src: yes
    owner: "admin" 
    group: "admin"
  become: yes
