---
- name: "Install lvm utils (RedHat)"
  become: true
  yum:
      name: "lvm2"
      state: "present"
  when: "ansible_os_family == 'RedHat'"

- name: "Get volume group information."
  become: true
  shell: "pvs /dev/sdb --option vg_name | tail -n+2"
  register: "volume_groups"
  ignore_errors: yes
  changed_when: false

- name: "Remove volume groups."
  become: true
  command: "vgremove {{ volume_group }} --yes"
  with_items: "{{ volume_groups.stdout_lines }}"
  loop_control: { loop_var: "volume_group" }
  ignore_errors: yes

- name: "Remove physical volume from cluster disks."
  become: true
  command: "pvremove /dev/sdb --yes"
  ignore_errors: yes

- name: "Remove lvm utils (RedHat)"
  become: true
  yum:
      name: "lvm2"
      state: "absent"
  when: "ansible_os_family == 'RedHat'"
