---
- name: destroy an instance
  gcp_compute_instance:
    state: "absent"
    name: "{{ instance_name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance

- name: destroy a disk
  gcp_compute_disk:
    name: "{{ instance_name }}-bootdisk"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: "absent"
  register: bootdisk

- name: destroy a disk
  gcp_compute_disk:
    name: "{{ instance_name }}-datadisk"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: "absent"