---

- name: Creates nodes
  hosts: localhost
  gather_facts: False
  vars:
    gcp_project: tidal-datum-246513
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ../service-account-private-key.json
    region: europe-west2
    scopes:
      - https://www.googleapis.com/auth/compute
  roles:
    - { role: ../roles/infra-provisioning/create-k8s-node, vars: [{ zone: 'europe-west2-a' }, { instance_name: 'master1a' }, { instance_tags: ['bootstrap', 'control-plane', 'k8s-cluster'] }], tags: ['phase1']}
    - { role: ../roles/infra-provisioning/create-k8s-node, vars: [{ zone: 'europe-west2-a' }, { instance_name: 'node1a' }, { instance_tags: ['workers', 'gfs-cluster', 'heketi-node', 'k8s-cluster'] }], tags: ['phase1']}
    - { role: ../roles/infra-provisioning/create-k8s-node, vars: [{ zone: 'europe-west2-b' }, { instance_name: 'node2b' }, { instance_tags: ['workers', 'gfs-cluster', 'heketi-node', 'k8s-cluster'] }], tags: ['phase1']}
    - { role: ../roles/infra-provisioning/create-k8s-node, vars: [{ zone: 'europe-west2-c' }, { instance_name: 'node3c' }, { instance_tags: ['workers', 'gfs-cluster', 'heketi-node', 'k8s-cluster'] }], tags: ['phase1']}

- name: Create instance group
  hosts: localhost
  gather_facts: False
  vars:
    gcp_project: tidal-datum-246513
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ../service-account-private-key.json
    region: europe-west2
    scopes:
      - https://www.googleapis.com/auth/compute  
  tasks:
    - name: create a network
      gcp_compute_network:
        name: default
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: network
      tags: ['phase2']

    - name: create a instance group
      gcp_compute_instance_group:
        name: mstakx-instance-group
        instances:
          - {'selfLink' : "https://www.googleapis.com/compute/v1/projects/{{ gcp_project }}/zones/{{ region }}-a/instances/master1a"}
          - {'selfLink' : "https://www.googleapis.com/compute/v1/projects/{{ gcp_project }}/zones/{{ region }}-a/instances/node1a"}
        named_ports:
        - name: http
          port: 32727
        network: "{{ network }}"
        zone: "{{ region }}-a"
        project: "{{ gcp_project }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      tags: ['phase2']

- name: Prepare nodes
  hosts: tag_k8s-cluster
  gather_facts: True
  roles:
    - { role: ../roles/k8s-setup/reset, tags: ['phase3']}
    - { role: ../roles/k8s-setup/prepare-node, tags: ['phase3']}

- name: Setup bootstraping master
  hosts: tag_bootstrap
  gather_facts: True
  roles:
    - { role: ../roles/k8s-setup/setup-first-master, tags: ['k8s'] }
    - { role: ../roles/k8s-setup/setup-network, tags: ['k8s'] }

- name: Setup remaining masters
  hosts: tag_othermasters
  gather_facts: True
  become: yes
  roles:
    - { role: ../roles/k8s-setup/setup-remaining-masters, tags: ['k8s'] }

- name: Setup workers
  hosts: tag_workers
  gather_facts: True
  become: yes
  roles:
    - { role: ../roles/k8s-setup/setup-workers, tags: ['k8s'] }

- hosts: tag_heketi-node
  roles:
    - { role: ../roles/heketi/prepare, tags: ['storage'] }

- hosts: tag_bootstrap
  tags:
    - "provision"
  roles:
    - { role: ../roles/heketi/provision, tags: ['storage'] }

- name: Install apps
  hosts: tag_k8s-cluster
  gather_facts: False
  roles:
    - { role: ../roles/apps-setup/nginx-ingress-controller-setup, tags: ["apps"] }
    - { role: ../roles/apps-setup/guestbook-setup, tags: ["apps", "gb"] }
    - { role: ../roles/apps-setup/registry-setup, tags: ["apps"] }
    - { role: ../roles/apps-setup/helm-setup, tags: ["apps", "helm"] }
    - { role: ../roles/apps-setup/grafana-setup, tags: ["apps", "graf"] }
    - { role: ../roles/apps-setup/prometheus-setup, tags: ["apps", "prom"] }
    - { role: ../roles/apps-setup/efk-setup, tags: ["apps", "efk"] }
    - { role: ../roles/apps-setup/jenkins-setup, tags: ["apps", "jenk"] }
    - { role: ../roles/apps-setup/istio-setup, tags: ["apps", "istio"] }
    - { role: ../roles/apps-setup/clair-setup, tags: ["apps", "clair"] }
    - { role: ../roles/apps-setup/mediawiki-setup, tags: ["apps", "mw"] }
