---
- name: Create working directory
  file: path=/tmp/registry-setup state=directory
  when:
    - inventory_hostname == 'master1a'

- name: Deploy docker registry manifests
  copy:
    src: "{{ item }}"
    dest: "/tmp/registry-setup/{{ item }}"
  with_items:
    - 00-namespace.yaml
    - 01-deployment.yaml
    - 02-service.yaml
  when:
    - inventory_hostname == 'master1a'

- name: Deploy docker registry manifests
  copy:
    src: "{{ playbook_dir }}/{{ item }}"
    dest: "/tmp/registry-setup/{{ item }}"
  with_items:
    - ca.crt
    - ca.key
  when:
    - inventory_hostname == 'master1a'

- name: Apply docker registry manifests
  command: kubectl apply -f /tmp/registry-setup
  when:
    - inventory_hostname == 'master1a'

- name: Create docker registry config map containing keys
  command: kubectl -n docker-registry create configmap docker-registry-keys --from-file=/tmp/registry-setup/ca.crt --from-file=/tmp/registry-setup/ca.key
  when:
    - inventory_hostname == 'master1a'

- name: Clean working directory
  file: path=/tmp/registry-setup state=absent
  when:
    - inventory_hostname == 'master1a'
